#!/bin/bash
# One-click Vercel deploy for github-readme-stats

echo "🚀 Setting up self-hosted GitHub Readme Stats..."
echo ""
echo "Your fork is ready at: https://github.com/RahulRachhoya/github-readme-stats"
echo ""
echo "=== Deployment Options ==="
echo ""
echo "Option 1: One-Click Deploy (Easiest)"
echo "------------------------------------"
echo "1. Visit: https://vercel.com/new"
echo "2. Import your fork: RahulRachhoya/github-readme-stats"
echo "3. In 'Environment Variables', add:"
echo "   Name:  PAT_1"
echo "   Value: <your_github_pat>"
echo "4. Click Deploy"
echo ""
echo "Option 2: GitHub Actions Auto-Deploy"
echo "------------------------------------"
echo "Add .github/workflows/deploy.yml to your fork"
echo ""
echo "Option 3: Use Already-Working Service"
echo "-------------------------------------"
echo "Alternative: gstsf.dev (strips deps) https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app"
echo ""
echo "=== Get GitHub PAT ==="
echo "1. Go to: https://github.com/settings/tokens/new"
echo "2. Name: github-readme-stats"
echo "3. Select: read:user, public_repo"
echo "4. Generate token"
echo ""
read -p "Press Enter when deployed to continue..."
